<%
klang = Request.Cookies("klang")
language_tr = "="
language_en = "="
language_en = language_en & "||Çıkış=Logout"
language_en = language_en & "||Her Hakkı Saklıdır=All Rights Reserved"
language_en = language_en & "||Ad Soyad=Name Surname"
language_en = language_en & "||ARA=Search"
language_en = language_en & "||YENİ HASTA=New Patient"
language_en = language_en & "||Not=Note"
language_en = language_en & "||Tarih=Date"
language_en = language_en & "||Acenta=Agency"
language_en = language_en & "||Refakatci Bilgileri=Companion Info"
language_en = language_en & "||Ameliyat Bilgileri=Surgery Info"
language_en = language_en & "||Ödeme Bilgileri=Payment Info"
language_en = language_en & "||Uçuş Bilgileri=Flight Info"
language_en = language_en & "||Konaklama Bilgileri=Accommodation Information"
language_en = language_en & "||Dosyalar=Files"
language_en = language_en & "||Hasta Bilgileri=Patient Info"
language_en = language_en & "||Ameliyat=Surgery"
language_en = language_en & "||Doktor=Doctor"
language_en = language_en & "||Hastane=Hospital"
language_en = language_en & "||Kaydet=Save"
language_en = language_en & "||{%1} için <strong>{%2}</strong> cinsinden ödeme bilgilerini yazın=Please type <strong>{%2}</strong> payment info for {%1}"
language_en = language_en & "||Hasta Adı Soyadı=Patient Name Surname"
language_en = language_en & "||GSM=GSM"
language_en = language_en & "||Eposta Adresi=Email Address"
language_en = language_en & "||Çağrı Kaynağı=Call Source"
language_en = language_en & "||Geldiği Ülke=Country"
language_en = language_en & "||Para Birimi=Currency"
language_en = language_en & "||Ayarlar=Settings"
language_en = language_en & "||Pasaport Numarası=Passport Number"
language_en = language_en & "||Refakatci Listesi=Companion List"
language_en = language_en & "||Sil=Delete"
language_en = language_en & "||Lütfen ameliyatın yapılacağı hastaneyi seçin=Please select the hospital where the surgery will be performed"
language_en = language_en & "||Lütfen ameliyatın yapılacağı tarihi seçin=Please select the date when the surgery will be performed"
language_en = language_en & "||Ameliyat Listesi=Surgery List"
language_en = language_en & "||Paket Fiyatı=Package Price"
language_en = language_en & "||Kaparo=Deposit"
language_en = language_en & "||Banka Dekontu=GG Number"
language_en = language_en & "||Banka Adı=Bank Name"
language_en = language_en & "||Personel=Employee"
language_en = language_en & "||İşlem=Process"
language_en = language_en & "||IP=IP"
language_en = language_en & "||Hareket Ayrıntıları=Process Details"
language_en = language_en & "||Uçuş Tarihi=Flight Date"
language_en = language_en & "||Uçuş Saati=Flight Time"
language_en = language_en & "||Uçak Kalkış Yeri=Departure Airport"
language_en = language_en & "||Uçak Numarası=Flight Number"
language_en = language_en & "||Uçak Firması=Airways"
language_en = language_en & "||Uçak İniş Havalimanı=Landing Airport"
language_en = language_en & "||Lütfen uçuş tarihini ve saatini yazın=Please write the flight date and time"
language_en = language_en & "||Transfer Listesi=Transfer List"
language_en = language_en & "||Transfer=Transfer"
language_en = language_en & "||Var=Yes"
language_en = language_en & "||Yok=No"
language_en = language_en & "||Konaklama Yeri=Accommodation place"
language_en = language_en & "||Check In=Check In"
language_en = language_en & "||Check Out=Check Out"
language_en = language_en & "||Kişi Sayısı=Number of Persons"
language_en = language_en & "||Oda Türü=Room Type"
language_en = language_en & "||Yatak Türü=Bed Type"
language_en = language_en & "||Konaklama Listesi=Accommodation List"
language_en = language_en & "||Hatalı konaklama tarihi seçtiniz. Giriş tarihi, çıkış tarihinden sonra olamaz=You have selected the wrong accommodation date. Check-in date cannot be later than check-out date"
language_en = language_en & "||Lütfen konaklama yerini seçin=Please select the patients accommodation"
language_en = language_en & "||Lütfen konaklama tarihini seçin=Please choose check in date"
language_en = language_en & "||Lütfen konaklama ayrıntılarını seçin=Please select the patients accommodation details"
language_en = language_en & "||Lütfen hasta iletişim bilgilerini yazın=Please write patient contact information"
language_en = language_en & "||Sorumlu Operasyon Personeli=Responsible Operations Personnel"
language_en = language_en & "||Lütfen acenta seçin=Please select agent"
language_en = language_en & "||Lütfen para birimi seçin=Please select currency"
language_en = language_en & "||Lütfen hastanın geleceği ülkeyi seçin=Please select the country from which the patient will come"
language_en = language_en & "||Lütfen çağrı kaynağını seçin=Please select the call source"
language_en = language_en & "||Refakatci Adı Soyadı=Companion Name Surname"
language_en = language_en & "||Refakatci Pasaport Numarası=Companion Passport Number"
language_en = language_en & "||Transfer Bilgileri Güncellendi=Transfer Information Updated"
language_en = language_en & "||Please type GG number=Please type GG number"
language_en = language_en & "||Please type surgery price informations=Please type surgery price informations"
language_en = language_en & "||Ödeme Bilgileri Güncellendi=Payment Information Updated"
language_en = language_en & "||Yeni Personel Ekle=Add New Personnel"
language_en = language_en & "||Pozisyon=Position"
language_en = language_en & "||Son Giriş=Last Login"
language_en = language_en & "||Personel Bilgilerini Düzenle=Edit Personnel Information"
language_en = language_en & "||Personel Adı Soyadı=Personnel Name Surname"
language_en = language_en & "||Şifre=Password"
language_en = language_en & "||Bu işlemi yapmak için yeterli yetkiniz bulunmamaktadır=You do not have sufficient privileges to perform this operation."
language_en = language_en & "||Hatalı email adresi yazdınız=Hatalı email adresi yazdınız"
language_en = language_en & "||Son Kullanma Tarihi=Expiration Date"
language_en = language_en & "||Lütfen yeni şifrenizi yazın=Please type new password"
language_en = language_en & "||Güncelle=Update"
language_en = language_en & "||Lütfen email adresini yazın=Please type your email address"
language_en = language_en & "||Lütfen şifrenizi yazın=Please type password"
language_en = language_en & "||Personel Yetkileri=User Authorizations"
language_en = language_en & "||Yetki : =Authority : "
language_en = language_en & "||Yönetici=Manager"
language_en = language_en & "||Yetki Güncellendi=Authorizations Updated"
language_en = language_en & "||Giriş Yapamaz=Giriş Yapamaz"
language_en = language_en & "||Kalkış Saati=Kalkış Saati"
language_en = language_en & "||Varış Saati=Arrival Time"
language_en = language_en & "||Uçuş Numarası=Uçuş Numarası"
language_en = language_en & "||Uçak İniş Yeri=Arival Airport"
language_en = language_en & "||Sorumlu Personel=Responsible Personnel"
language_en = language_en & "||Öncelik=Öncelik"
language_en = language_en & "||Arıza Başlığı=Arıza Başlığı"
language_en = language_en & "||Arıza Ayrıntıları=Arıza Ayrıntıları"
language_en = language_en & "||ARIZA BİLDİR=ARIZA BİLDİR"
language_en = language_en & "||Ünvan=Title"
language_en = language_en & "||Dahili=Internal"
language_en = language_en & "||YENİ ETİKET=NEW LABEL"
language_en = language_en & "||Stok Kodu - Stok Adı=Product Name - Code"
language_en = language_en & "||Stok Kodu=Product Code"
language_en = language_en & "||Stok Adı=Product Name"
language_en = language_en & "||Mamül Adı=Mamül Adı"
language_en = language_en & "||Etiket Dili=Etiket Dili"
language_en = language_en & "||Menşei=Menşei"
language_en = language_en & "||Ölçü=Ölçü"
language_en = language_en & "||Durum=Status"
language_en = language_en & "||Grubu=Grubu"
language_en = language_en & "||Etiket Ayrıntıları=Etiket Ayrıntıları"
language_en = language_en & "||Dil=Lang"
language_en = language_en & "||Etiket Ölçüsü=Etiket Ölçüsü"
language_en = language_en & "||Etiket Durumu=Etiket Durumu"
language_en = language_en & "||Revizyon=Revizyon"
language_en = language_en & "||Pantone Kodu=Pantone Kodu"
language_en = language_en & "||Son Güncelleme=Last Update"
language_en = language_en & "||Açıklama=Açıklama"
language_en = language_en & "||Yeni Revizyon Olarak Kaydet=Yeni Revizyon Olarak Kaydet"
language_en = language_en & "||Revizyon numarasını değiştrmeyi unuttunuz=Revizyon numarasını değiştrmeyi unuttunuz"
language_en = language_en & "||Lütfen stok kodunu yazın=Please type product code"
language_en = language_en & "||Lütfen stok adını yazın=Please type product name"
language_en = language_en & "||Lütfen mamül adını yazın=Lütfen mamül adını yazın"
language_en = language_en & "||Lütfen revizyon adını yazın=Lütfen revizyon adını yazın"
language_en = language_en & "||Lütfen etiket ölçüsünü yazın=Lütfen etiket ölçüsünü yazın"
language_en = language_en & "||Lütfen durdurulma sebebini açıklama alanına yazın=Lütfen durdurulma sebebini açıklama alanına yazın"
language_en = language_en & "||Lütfen mensei yazın=Lütfen mensei yazın"
language_en = language_en & "||Girmiş olduğunuz stok kodlu etiket daha önce eklenmiş.<br />Yeni ekleme yapılmadı=Girmiş olduğunuz stok kodlu etiket daha önce eklenmiş.<br />Yeni ekleme yapılmadı"
language_en = language_en & "||Dosya Ayrıntıları=Dosya Ayrıntıları"
language_en = language_en & "||Dosya Yükleme=Dosya Yükleme"
language_en = language_en & "||Resim Dosyası=Resim Dosyası"
language_en = language_en & "||Yüklenen Dosya Açıklaması=Yüklenen Dosya Açıklaması"
language_en = language_en & "||Yükle=Yükle"
language_en = language_en & "||Dosya başarıyla yüklendi=Dosya başarıyla yüklendi"
language_en = language_en & "||Bir hata oluştu=Bir hata oluştu"
language_en = language_en & "||Dosyayı İndir=Dosyayı İndir"
language_en = language_en & "||Sipariş No=Sipariş No"
language_en = language_en & "||Cari Kodu=Current Code"
language_en = language_en & "||Grup Kodu=Group Code"
language_en = language_en & "||Cinsi=Cinsi"
language_en = language_en & "||Sipariş Tarihi=Sipariş Tarihi"
language_en = language_en & "||Teslim Tarihi=Teslim Tarihi"
language_en = language_en & "||Kalite Sonuç=Kalite Sonuç"
language_en = language_en & "||TD Puanı=TD Puanı"
language_en = language_en & "||Dashboard dizilimini değiştir=Change dashboard layout"
language_en = language_en & "||Hava Durumu=Weather Forecast"
language_en = language_en & "||Döviz Kurları=Exchange"
language_en = language_en & "||Özel Kur Güncelle=Custom Rate Updates"
language_en = language_en & "||TCMBden Çek=Update from TCMB"
language_en = language_en & "||Hesapla=Calculate"
language_en = language_en & "||Döviz kurlarını güncelleme yetkiniz bulunmamaktadır=You are not authorized to update exchange rates"
language_en = language_en & "||Anlık=Now"
language_en = language_en & "||Yarın=Tomorrow"
language_en = language_en & "||En Yüksek=Highest"
language_en = language_en & "||En Düşük=Lowest"
language_en = language_en & "||Gece=Night"
language_en = language_en & "||Nem=Humid"
language_en = language_en & "||Tamam=Okay"
language_en = language_en & "||Cari Adı, Cari Kodu=Customer Name"
language_en = language_en & "||Sayı=Number"
language_en = language_en & "||Cari Ad=Customer Name"
language_en = language_en & "||Teklif Türü=Offer Type"
language_en = language_en & "||Sonuç=Result"
language_en = language_en & "||Teklifleri görmek için yeterli yetkiniz bulunmamaktadır=You do not have sufficient privileges to view Offers"
language_en = language_en & "||Koşullar=Conditions"
language_en = language_en & "||Şablon Bulunamadı=Template Not Found"
language_en = language_en & "||Üst Yazılar=Header"
language_en = language_en & "||Ön yazı bulunamadı=Cover letter not found"
language_en = language_en & "||Cari Ad veya Kod=Customer Name"
language_en = language_en & "||CARİ ARA=Find Customer"
language_en = language_en & "||Grup Atamaları=Group Assignments"
language_en = language_en & "||Cari Seçimi=Choice Customer"
language_en = language_en & "||Müşteri Bilgileri=Customer Informations"
language_en = language_en & "||Sayın=Dear"
language_en = language_en & "||Sayı : (Boş bırakırsanız otomatik oluşur)=Number : (If you leave it blank, it will be created automatically)"
language_en = language_en & "||Teklif Tarihi=Offer Date"
language_en = language_en & "||Teklif Ayarları=Offer Settings"
language_en = language_en & "||Teklif Veren Firma=Offering Firm"
language_en = language_en & "||Teklif Dili=Offer Landuage"
language_en = language_en & "||Türkçe=Turkish"
language_en = language_en & "||İngilizce=English"
language_en = language_en & "||Teklif Para Birimi=Offer Currency"
language_en = language_en & "||Teklif Tasarımı=Offer Design"
language_en = language_en & "||Teklif Ön Yazısı=Offer Cover Letter"
language_en = language_en & "||Hazır Yazı=Stock Text"
language_en = language_en & "||Ürünler=Product"
language_en = language_en & "||Katalog Kodu=Catalogue Code"
language_en = language_en & "||Müşteri Referans Kodu=Customer Reference Code"
language_en = language_en & "||Teklif Verilecek Ürün=Product to be Offered"
language_en = language_en & "||Ürün adı, stok kodu, barkod=Product Name"
language_en = language_en & "||Ekle=Add"
language_en = language_en & "||Teklife Özel Not=Special Note to Offer"
language_en = language_en & "||Ticari Koşullar=Commercial Terms"
language_en = language_en & "||Teklif Alt Yazısı=Offer footer text"
language_en = language_en & "||Alt Yazı=Footer Text"
language_en = language_en & "||Ürün eklemeden önce teklif verilecek olan firmaya ait cari bilgilerini girmelisiniz.=Before adding a product, you must enter the company information of the company to which the offer will be made."
language_en = language_en & "||Lütfen bir ürün seçin.=Please select a product"
language_en = language_en & "||HAYIR=NO"
language_en = language_en & "||EVET=YES"
language_en = language_en & "||Hazırlanıyor=Preparing"
language_en = language_en & "||Amir Onayında=Waiting Supervisor Approval"
language_en = language_en & "||Amir Onaylı=Supervisor Approved"
language_en = language_en & "||Amir Red=Supervisor Rejected"
language_en = language_en & "||Müşteriye Gönderildi=Sended to Customer"
language_en = language_en & "||Müşteri Red=Customer Rejected"
language_en = language_en & "||Satış Gerçekleşti=Sale Made"
language_en = language_en & "||Ödeme Bekleniyor=Payment Awaiting"
language_en = language_en & "||Sevkiyatta=In Shipment"
language_en = language_en & "||Kdv Dahil Toplamlı Teklif=Total Offer Including VAT"
language_en = language_en & "||Kdv Hariç Toplamlı Teklif=Total Offer Excluding VAT"
language_en = language_en & "||Genel Teklif=General Offer"
language_en = language_en & "||Mail Order=Mail Order"
language_en = language_en & "||Taksitli Mail Order=Installment Mail Order"
language_en = language_en & "||İhracat Teklif=Export Offer"
language_en = language_en & "||Proforma Fatura=Proforma Invoice"
language_en = language_en & "||Üst Yazı=Offer header text"
language_en = language_en & "||Kod=Code"
language_en = language_en & "||Cari Adı=Customer Name"
language_en = language_en & "||İl=City"
language_en = language_en & "||Vergi No=Tax Number"
language_en = language_en & "||Firma Adı=Company Name"
language_en = language_en & "||Görev=Görev"
language_en = language_en & "||Bildirim Yöntemi=Notification Priority"
language_en = language_en & "||İçerik=Content"
language_en = language_en & "||Tür=Type"
language_en = language_en & "||Departman=Department"
language_en = language_en & "||Teklif verebilmek için yeterli yetkiniz bulunmamaktadır=You do not have sufficient authority to submit an offer."
language_en = language_en & "||Teklif ayarlarını görmek için yeterli yetkiniz bulunmamaktadır=You do not have sufficient privileges to view offer settings"
language_en = language_en & "||Teklif Kaydedildi=Offer Saved"
language_en = language_en & "||Önizleme=Preview"
language_en = language_en & "||Teklifi Amir Onayına Gönder?=Submit Offer to Supervisor Approval"
language_en = language_en & "||Amir Onayına Gönder=Submit to Supervisor Approval"
language_en = language_en & "||Gönderme=Don't Send"
language_en = language_en & "||Teklifi Amir Onaylına Gönder=Submit Offer to Supervisor Approval"
language_en = language_en & "||Teklifi Düzenle=Edit Offer"
language_en = language_en & "||Kritik Hata Oluştu. Teklif PDF için uygun rapor formatı bulunamadı=A Critical Error Occurred. No suitable report format found for offer PDF"
language_en = language_en & "||Teklif raporu formatı bulunamadı=There is no offer report format"
language_en = language_en & "||Koşul=Condition"
language_en = language_en & "||Yazı Yeri=Yazı Yeri"
language_en = language_en & "||Neresi=Where"
language_en = language_en & "||Teklif Üstü=Offer Header"
language_en = language_en & "||Teklif Altı=Offer Footer"
language_en = language_en & "||Ürün Altı=Under Product List"
language_en = language_en & "||Koşul Seçin=Please choice condition"
language_en = language_en & "||Kritik Hata Oluştu. Hatalı teklif=A Critical Error Occurred. Incorrect offer"
language_en = language_en & "||Birim Fiyat=Unit Price"
language_en = language_en & "||Adet=Piece"
language_en = language_en & "||Satır Toplamı=Row Total"
language_en = language_en & "||Toplam=Total"
language_en = language_en & "||Ara Toplam=Subtotal"
language_en = language_en & "||Toplam KDV=Total VAT"
language_en = language_en & "||Genel Toplam=Grand total"
language_en = language_en & "||Teklife ürün ekleniyor=Adding product to offer"
language_en = language_en & "||Teklif para birimi (%1) ile stok para birimi (%2) farklılar=Offer currency {%1} and stock currency {%2} different"
language_en = language_en & "||Teklif para birimi {%1} ile stok para birimi {%2} farklılar=Offer currency {%1} and stock currency {%2} different"
language_en = language_en & "||Ürün Adı=Product Name"
language_en = language_en & "||Ürün Notu=Product Note"
language_en = language_en & "||Birim=Unit"
language_en = language_en & "||İskonto=Discount"
language_en = language_en & "||Toplam Fiyat=Total Price"
language_en = language_en & "||Çift=Double"
language_en = language_en & "||Düzine=Dozen"
language_en = language_en & "||Rulo=Roll"
language_en = language_en & "||Bidon=Drum"
language_en = language_en & "||Kutu=Box"
language_en = language_en & "||Koli=Parcel"
language_en = language_en & "||Paket=Package"
language_en = language_en & "||Teklif Fiyatı=Offer Price"
language_en = language_en & "||TL Fiyatı=TL Price"
language_en = language_en & "||USD Fiyatı=USD Price"
language_en = language_en & "||Düzenle=Edit"
language_en = language_en & "||Seç=Select"
language_en = language_en & "||Teklifdeki ürün güncelleniyor=Updating the product in the offer"
language_en = language_en & "||Detay=Detail"
language_en = language_en & "||Birim Fiyatı=Unit Price"
language_en = language_en & "||Toplam İskonto=Total Discount"
language_en = language_en & "||KDV Hariç=Excluding VAT"
language_en = language_en & "||PDF Oluştur=Create PDF"
language_en = language_en & "||Koşulu silmek mi istiyorsunuz?=Want to delete the condition?"
language_en = language_en & "||Silme=Don't Delete"
language_en = language_en & "||Koşulu Sil=Delete Condition"
language_en = language_en & "||Yeni Banka Ekle=Add New Bank Account"
language_en = language_en & "||Hesap Adı=Account Name"
language_en = language_en & "||Hesap Döviz Türü=Account Currency Type"
language_en = language_en & "||Şube Adı=Bank Branch Name"
language_en = language_en & "||Şube No=Bank Branch Number"
language_en = language_en & "||Hesap No=Account Number"
language_en = language_en & "||SWIFT Kodu=SWIFT Code"
language_en = language_en & "||IBAN=IBAN"
language_en = language_en & "||Kullanım Dışı=Out Of Order"
language_en = language_en & "||Banka Düzenle=Edit Bank Account"
language_en = language_en & "||{%1} için grup abonelikleri={%1} için grup abonelikleri"
language_en = language_en & "||Grup Adı=Group Name"
language_en = language_en & "||Lütfen banka adını yazınız=Please type bank name"
language_en = language_en & "||Lütfen hesap adını yazınız=Please type account name"
language_en = language_en & "||Lütfen döviz tipini seçiniz.=Please choice currency type"
language_en = language_en & "||Lütfen IBAN numarasını yazınız.=Please type IBAN number"
language_en = language_en & "||Yeni banka eklendi=New bank added"
language_en = language_en & "||Banka bilgileri güncellendi=Bank informations updated"
language_en = language_en & "||Kritik Hata Oluştu. Genel teklif ayarlarında eksik var=A Critical Error Occurred. Missing in general offer settings"
language_en = language_en & "||Ürün Kodu=Product Code"
language_en = language_en & "||Barkod=Barcode"
language_en = language_en & "||Ürün=Product"
language_en = language_en & "||Sıfır olanları göster / gizle=Show / hide zeros"
language_en = language_en & "||Pasif ürünleri göster / gizle=Show / hide passives"
language_en = language_en & "||Muhasebe Yazılımı ile Senkronize Et=Sync with Accounting Software"
language_en = language_en & "||Yeni Ürün Ekle=Add New Product"
language_en = language_en & "||Ürün Bilgileri=Product Informations"
language_en = language_en & "||Temel Bilgiler=Basic Informations"
language_en = language_en & "||Ek Bilgiler=Detailed Informations"
language_en = language_en & "||Koli Tanımları=Package Definitions"
language_en = language_en & "||Ürünün İngilizce Adı=English Name of Product"
language_en = language_en & "||Stok Türü=Stock Type"
language_en = language_en & "||Minumum Stok Miktarı=Minimum Stock Quantity"
language_en = language_en & "||Raf Ömrü (Ay)=Shelf Life (Months)"
language_en = language_en & "||KDV Oranı=VAT Rate"
language_en = language_en & "||Ürün Ana Birimi=Product Main Unit"
language_en = language_en & "||Seçilen Koli=Choicen Package"
language_en = language_en & "||Kullanılacak ham koli seçimi=Raw parcel selection to be used"
language_en = language_en & "||Koli İçi Ürün Miktarı=Product Amount in a Box"
language_en = language_en & "||Koli Adı=Package Name"
language_en = language_en & "||Kullanılan Koli Adı=Used Package Name"
language_en = language_en & "||Lütfen ürün için bir stok kodu yazın.=Please type a stock code for the product."
language_en = language_en & "||Lütfen ürüne ait ana birimi seçin=Please select the base unit for the product"
language_en = language_en & "||Ürüne ait KDV ORANI bilgisini seçiniz=Select the VAT RATE information of the product"
language_en = language_en & "||Yeni ürün eklendi=New Product Added"
language_en = language_en & "||Ürün Bilgilerini Düzenle=Edit Product Informations"
language_en = language_en & "||Stok Miktarı=Stock Quantity"
language_en = language_en & "||Mamul=Product"
language_en = language_en & "||Yarı Mamul=Semi Product"
language_en = language_en & "||Bileşen=Component"
language_en = language_en & "||Hammadde=Raw Materials"
language_en = language_en & "||Silindi=Deleted"
language_en = language_en & "||Senkronize Muhasebe Yazılımına Kaydet=Senkronize Muhasebe Yazılımına Kaydet"
language_en = language_en & "||Ay=Month"
language_en = language_en & "||KDV=VAT"
language_en = language_en & "||Mal Kabul Kalite Kontrol Deposundan Mı Yapılsın?=Should Goods Receipt Be Made From Quality Control Warehouse?"
language_en = language_en & "||Stok Temel Bilgileri=Stock Basic Informations"
language_en = language_en & "||Fiyat Bilgileri=Price Information"
language_en = language_en & "||Depolama Bilgileri=Warehouse Informations"
language_en = language_en & "||LOT Takibi Yapılsın=LOT Tracking"
language_en = language_en & "||Koli, koli bandı gibi sarf malzemelerde LOT takibi yapılmayacağı için bu tip ürünlerde HAYIR seçilir.=Since LOT tracking cannot be performed on consumables such as parcels and duct tape, NO is selected for these types of products."
language_en = language_en & "||Perakende Satış Fiyatı=Retail Price"
language_en = language_en & "||Toptan Satış Fiyatı=Wholesale Price"
language_en = language_en & "||Toplu Ürün Yükle=Bulk Import"
language_en = language_en & "||Silinmişleri Göster=Show Deleted"
language_en = language_en & "||Stok Sıfır Olanları Gizle=Hide Zero Stock"
language_en = language_en & "||Stok Sıfır Olanları Göster=Show Zero Stock"
language_en = language_en & "||Seçtiğiniz kriterlerde kayıt bulunamadı=There is no records found for the criteria you selected"
language_en = language_en & "||Silinmişleri Gizle=Hide Deleted"
language_en = language_en & "||Hata Oluştu=Something went wrong"
language_en = language_en & "||Tanımlanmamış=Undefined"
language_en = language_en & "||Ürün bilgileri güncellendi=Product information updated"
language_en = language_en & "||Ürüne ait fiyat bilgisini yazınız=Write the price information of the product"
language_en = language_en & "||İşlem yaptığınız ürün bilgileri muhasebe yazılımınız ile entegre şekilde ayarlanmış. Güncellemeleri muhasebe yazılımınız üzerinden yapmalısınız.=The product information you are dealing with is integrated with your accounting software. You should make the updates through your accounting software."
language_en = language_en & "||Stok firma bilgilerini sonradan değiştiremezsiniz.=You cannot update the stock company information."
language_en = language_en & "||Ürüne ait para birimi bilgisini seçiniz=Select the currency information of the product"
language_en = language_en & "||Entegrasyon=Integration"
language_en = language_en & "||Cari Listesi Ekranı=Current List Screen"
language_en = language_en & "||Müşteri Adı=Customer Name"
language_en = language_en & "||Veri Aktarımı=Data Transfer"
language_en = language_en & "||Yeni Cari Ekle=Add New Current"
language_en = language_en & "||Telefonu=Phone"
language_en = language_en & "||Email=Email"
language_en = language_en & "||Şehir=City"
language_en = language_en & "||Firma Türü=Company Type"
language_en = language_en & "||Cari Bilgilerini Düzenle=Edit Current Info"
language_en = language_en & "||Cari Kod=Current Code"
language_en = language_en & "||Cari Türü=Current Type"
language_en = language_en & "||Vergi Dairesi=Tax Office"
language_en = language_en & "||Vergi Numarası=Tax Number"
language_en = language_en & "||Telefon=Phone"
language_en = language_en & "||Posta Kodu=Postal Code"
language_en = language_en & "||Email Adresi=Email Address"
language_en = language_en & "||Posta Adresi=Postal Address"
language_en = language_en & "||Lütfen cari adını yazın=Please type current name"
language_en = language_en & "||Kayıt Güncellendi=Record Updated"
language_en = language_en & "||Cari Ayrıntıları Ekranı=Current Details Screen"
language_en = language_en & "||Kayıt Yapıldı=Recorded"
language_en = language_en & "||Döviz kurları merkez bankasından çekildi ve güncellendi=Exchange rates pulled from the central bank and updated"
language_en = language_en & "||Ürünün Barkodu=Product Barcode"
language_en = language_en & "||Verileri İçeri Al=Import Data"
language_en = language_en & "||Verileri Dışarı Aktar=Export Data"
language_en = language_en & "||Son Kullanıcı=End User"
language_en = language_en & "||Bayi=Dealer"
language_en = language_en & "||Tedarikçi=Supplier"
language_en = language_en & "||Yeni döviz kurları=New currency rates"
language_en = language_en & "||Döviz kurları yazdığınız şekilde güncellendi=Exchange rates updated as you type"
language_en = language_en & "||Cari Güncelleme=Current Update"
language_en = language_en & "||Email Gönder=Email Gönder"
language_en = language_en & "||Teklifi Onaylıyor Musunuz?=Teklifi Onaylıyor Musunuz?"
language_en = language_en & "||Teklifi Onayla=Teklifi Onayla"
language_en = language_en & "||Teklifi Reddet=Teklifi Reddet"
language_tr = language_tr & "||Çıkış=Çıkış"
language_tr = language_tr & "||Her Hakkı Saklıdır=Her Hakkı Saklıdır"
language_tr = language_tr & "||Uçuş Tarihi=Uçuş Tarihi"
language_tr = language_tr & "||Uçuş Saati=Uçuş Saati"
language_tr = language_tr & "||Uçak Kalkış Yeri=Uçak Kalkış Yeri"
language_tr = language_tr & "||Uçak Numarası=Uçak Numarası"
language_tr = language_tr & "||Uçak Firması=Uçak Firması"
language_tr = language_tr & "||Uçak İniş Havalimanı=Uçak İniş Havalimanı"
language_tr = language_tr & "||Ayarlar=Ayarlar"
language_tr = language_tr & "||Cihaz=Cihaz"
language_tr = language_tr & "||Marka=Marka"
language_tr = language_tr & "||Model=Model"
language_tr = language_tr & "||Son Akış=Son Akış"
language_tr = language_tr & "||Kontrol=Kontrol"
language_tr = language_tr & "||Durum=Durum"
language_tr = language_tr & "||Tarih=Tarih"
language_tr = language_tr & "||Ad Soyad=Ad Soyad"
language_tr = language_tr & "||ARA=ARA"
language_tr = language_tr & "||Yeni Personel Ekle=Yeni Personel Ekle"
language_tr = language_tr & "||Pozisyon=Pozisyon"
language_tr = language_tr & "||Son Giriş=Son Giriş"
language_tr = language_tr & "||Personel Bilgilerini Düzenle=Personel Bilgilerini Düzenle"
language_tr = language_tr & "||Personel Adı Soyadı=Personel Adı Soyadı"
language_tr = language_tr & "||GSM=GSM"
language_tr = language_tr & "||Şifre=Şifre"
language_tr = language_tr & "||Eposta Adresi=Eposta Adresi"
language_tr = language_tr & "||Kaydet=Kaydet"
language_tr = language_tr & "||Personel=Personel"
language_tr = language_tr & "||İşlem=İşlem"
language_tr = language_tr & "||IP=IP"
language_tr = language_tr & "||Bilgiler Güncellendi=Bilgiler Güncellendi"
language_tr = language_tr & "||Son Kullanma Tarihi=Son Kullanma Tarihi"
language_tr = language_tr & "||Lütfen yeni şifrenizi yazın=Lütfen yeni şifrenizi yazın"
language_tr = language_tr & "||Güncelle=Güncelle"
language_tr = language_tr & "||Personel Yetkileri=Personel Yetkileri"
language_tr = language_tr & "||Giriş Yapamaz=Giriş Yapamaz"
language_tr = language_tr & "||Yönetici=Yönetici"
language_tr = language_tr & "||Yetki : =Yetki : "
language_tr = language_tr & "||YENİ HASTA=YENİ HASTA"
language_tr = language_tr & "||Not=Not"
language_tr = language_tr & "||Acenta=Acenta"
language_tr = language_tr & "||Ameliyat Bilgileri=Ameliyat Bilgileri"
language_tr = language_tr & "||Ödeme Bilgileri=Ödeme Bilgileri"
language_tr = language_tr & "||Uçuş Bilgileri=Uçuş Bilgileri"
language_tr = language_tr & "||Konaklama Bilgileri=Konaklama Bilgileri"
language_tr = language_tr & "||Refakatci Bilgileri=Refakatci Bilgileri"
language_tr = language_tr & "||Dosyalar=Dosyalar"
language_tr = language_tr & "||Hasta Bilgileri=Hasta Bilgileri"
language_tr = language_tr & "||Ameliyat=Ameliyat"
language_tr = language_tr & "||Doktor=Doktor"
language_tr = language_tr & "||Hastane=Hastane"
language_tr = language_tr & "||Ameliyat Listesi=Ameliyat Listesi"
language_tr = language_tr & "||Sil=Sil"
language_tr = language_tr & "||{%1} için <strong>{%2}</strong> cinsinden ödeme bilgilerini yazın={%1} için <strong>{%2}</strong> cinsinden ödeme bilgilerini yazın"
language_tr = language_tr & "||Paket Fiyatı=Paket Fiyatı"
language_tr = language_tr & "||Kaparo=Kaparo"
language_tr = language_tr & "||Banka Dekontu=Banka Dekontu"
language_tr = language_tr & "||Hareket Ayrıntıları=Hareket Ayrıntıları"
language_tr = language_tr & "||Transfer Listesi=Transfer Listesi"
language_tr = language_tr & "||Transfer=Transfer"
language_tr = language_tr & "||Var=Var"
language_tr = language_tr & "||Transfer Bilgileri Güncellendi=Transfer Bilgileri Güncellendi"
language_tr = language_tr & "||Konaklama Yeri=Konaklama Yeri"
language_tr = language_tr & "||Check In=Check In"
language_tr = language_tr & "||Check Out=Check Out"
language_tr = language_tr & "||Kişi Sayısı=Kişi Sayısı"
language_tr = language_tr & "||Oda Türü=Oda Türü"
language_tr = language_tr & "||Yatak Türü=Yatak Türü"
language_tr = language_tr & "||Refakatci Adı Soyadı=Refakatci Adı Soyadı"
language_tr = language_tr & "||Refakatci Pasaport Numarası=Refakatci Pasaport Numarası"
language_tr = language_tr & "||Yetki Güncellendi=Yetki Güncellendi"
language_tr = language_tr & "||Konaklama Listesi=Konaklama Listesi"
language_tr = language_tr & "||Refakatci Listesi=Refakatci Listesi"
language_tr = language_tr & "||Pasaport Numarası=Pasaport Numarası"
language_tr = language_tr & "||Öncelik=Öncelik"
language_tr = language_tr & "||Sorumlu Personel=Sorumlu Personel"
language_tr = language_tr & "||Arıza Başlığı=Arıza Başlığı"
language_tr = language_tr & "||Arıza Ayrıntıları=Arıza Ayrıntıları"
language_tr = language_tr & "||ARIZA BİLDİR=ARIZA BİLDİR"
language_tr = language_tr & "||Stok Kodu - Stok Adı=Stok Kodu - Stok Adı"
language_tr = language_tr & "||YENİ ETİKET=YENİ ETİKET"
language_tr = language_tr & "||Stok Kodu=Stok Kodu"
language_tr = language_tr & "||Revizyon=Revizyon"
language_tr = language_tr & "||Stok Adı=Stok Adı"
language_tr = language_tr & "||Mamül Adı=Mamül Adı"
language_tr = language_tr & "||Etiket Dili=Etiket Dili"
language_tr = language_tr & "||Menşei=Menşei"
language_tr = language_tr & "||Grubu=Grubu"
language_tr = language_tr & "||Ölçü=Ölçü"
language_tr = language_tr & "||Son Güncelleme=Son Güncelleme"
language_tr = language_tr & "||Etiket Ayrıntıları=Etiket Ayrıntıları"
language_tr = language_tr & "||Dil=Dil"
language_tr = language_tr & "||Etiket Ölçüsü=Etiket Ölçüsü"
language_tr = language_tr & "||Pantone Kodu=Pantone Kodu"
language_tr = language_tr & "||Etiket Durumu=Etiket Durumu"
language_tr = language_tr & "||Açıklama=Açıklama"
language_tr = language_tr & "||Yeni Revizyon Olarak Kaydet=Yeni Revizyon Olarak Kaydet"
language_tr = language_tr & "||Revizyon numarasını değiştrmeyi unuttunuz=Revizyon numarasını değiştrmeyi unuttunuz"
language_tr = language_tr & "||Lütfen durdurulma sebebini açıklama alanına yazın=Lütfen durdurulma sebebini açıklama alanına yazın"
language_tr = language_tr & "||Lütfen stok kodunu yazın=Lütfen stok kodunu yazın"
language_tr = language_tr & "||Lütfen stok adını yazın=Lütfen stok adını yazın"
language_tr = language_tr & "||Lütfen mamül adını yazın=Lütfen mamül adını yazın"
language_tr = language_tr & "||Lütfen mensei yazın=Lütfen mensei yazın"
language_tr = language_tr & "||Lütfen revizyon adını yazın=Lütfen revizyon adını yazın"
language_tr = language_tr & "||Lütfen etiket durumunu seçin=Lütfen etiket durumunu seçin"
language_tr = language_tr & "||Lütfen etiket ölçüsünü yazın=Lütfen etiket ölçüsünü yazın"
language_tr = language_tr & "||Dahili=Dahili"
language_tr = language_tr & "||Ünvan=Ünvan"
language_tr = language_tr & "||Dosya Ayrıntıları=Dosya Ayrıntıları"
language_tr = language_tr & "||Resim Dosyası=Resim Dosyası"
language_tr = language_tr & "||PDF Dosyası=PDF Dosyası"
language_tr = language_tr & "||Yüklenen Dosya Açıklaması=Yüklenen Dosya Açıklaması"
language_tr = language_tr & "||Yükle=Yükle"
language_tr = language_tr & "||Dosya başarıyla yüklendi=Dosya başarıyla yüklendi"
language_tr = language_tr & "||Dosya Yükleme=Dosya Yükleme"
language_tr = language_tr & "||Dosyayı İndir=Dosyayı İndir"
language_tr = language_tr & "||Hasta Adı Soyadı=Hasta Adı Soyadı"
language_tr = language_tr & "||Çağrı Kaynağı=Çağrı Kaynağı"
language_tr = language_tr & "||Geldiği Ülke=Geldiği Ülke"
language_tr = language_tr & "||Para Birimi=Para Birimi"
language_tr = language_tr & "||Sorumlu Operasyon Personeli=Sorumlu Operasyon Personeli"
language_tr = language_tr & "||Varış Saati=Varış Saati"
language_tr = language_tr & "||Cari Kodu=Cari Kodu"
language_tr = language_tr & "||Sipariş No=Sipariş No"
language_tr = language_tr & "||Grup Kodu=Grup Kodu"
language_tr = language_tr & "||Sipariş Tarihi=Sipariş Tarihi"
language_tr = language_tr & "||Kalite Sonuç=Kalite Sonuç"
language_tr = language_tr & "||TD Puanı=TD Puanı"
language_tr = language_tr & "||Cinsi=Cinsi"
language_tr = language_tr & "||Teslim Tarihi=Teslim Tarihi"
language_tr = language_tr & "||Kayıt Oluşturan Personel=Kayıt Oluşturan Personel"
language_tr = language_tr & "||Sipariş Miktarı=Sipariş Miktarı"
language_tr = language_tr & "||Teslim Miktarı=Teslim Miktarı"
language_tr = language_tr & "||Teslimat Sayısı=Teslimat Sayısı"
language_tr = language_tr & "||Teslim Gün=Teslim Gün"
language_tr = language_tr & "||Sipariş No - Cari Kod=Sipariş No - Cari Kod"
language_tr = language_tr & "||Fiş No=Fiş No"
language_tr = language_tr & "||Cari Bul=Cari Bul"
language_tr = language_tr & "||Cari Adı=Cari Adı"
language_tr = language_tr & "||Cari Kodu - Cari Adı=Cari Kodu - Cari Adı"
language_tr = language_tr & "||Hatalı email adresi yazdınız=Hatalı email adresi yazdınız"
language_tr = language_tr & "||Ürün=Ürün"
language_tr = language_tr & "||Kod=Kod"
language_tr = language_tr & "||Ürün Adı=Ürün Adı"
language_tr = language_tr & "||Tür=Tür"
language_tr = language_tr & "||Stok Düzenle=Stok Düzenle"
language_tr = language_tr & "||Cari Düzenle=Cari Düzenle"
language_tr = language_tr & "||Lütfen email adresini yazın=Lütfen email adresini yazın"
language_tr = language_tr & "||Reçete Düzenle=Reçete Düzenle"
language_tr = language_tr & "||Reçete Adımları Düzenle=Reçete Adımları Düzenle"
language_tr = language_tr & "||Reçete Adım Düzenle=Reçete Adım Düzenle"
language_tr = language_tr & "||Reçete Kopyala=Reçete Kopyala"
language_tr = language_tr & "||Yukarı Taşı=Yukarı Taşı"
language_tr = language_tr & "||Aşağı Taşı=Aşağı Taşı"
language_tr = language_tr & "||Kayıt bulunamadı=Kayıt bulunamadı"
language_tr = language_tr & "||Hepsi=Hepsi"
language_tr = language_tr & "||Sayfa başına _MENU_ kayıt gösteriliyor=Sayfa başına _MENU_ kayıt gösteriliyor"
language_tr = language_tr & "||_PAGE_ - _PAGES_ arası sayfalar gösteriliyor=_PAGE_ - _PAGES_ arası sayfalar gösteriliyor"
language_tr = language_tr & "||(_MAX_ kayıt filtreleniyor)=(_MAX_ kayıt filtreleniyor)"
language_tr = language_tr & "||Veri Bulunamadı=Veri Bulunamadı"
language_tr = language_tr & "||Yükleniyor=Yükleniyor"
language_tr = language_tr & "||İşleniyor=İşleniyor"
language_tr = language_tr & "||İlk=İlk"
language_tr = language_tr & "||Son=Son"
language_tr = language_tr & "||Sonraki=Sonraki"
language_tr = language_tr & "||Önceki=Önceki"
language_tr = language_tr & "||Ara :=Ara :"
language_tr = language_tr & "||Rapor Adı=Rapor Adı"
language_tr = language_tr & "||Rapor Türü=Rapor Türü"
language_tr = language_tr & "||SQL Sorgusu=SQL Sorgusu"
language_tr = language_tr & "||Düzenle=Düzenle"
language_tr = language_tr & "||YENİ CARİ=YENİ CARİ"
language_tr = language_tr & "||Cari Kod=Cari Kod"
language_tr = language_tr & "||Cari Ad=Cari Ad"
language_tr = language_tr & "||Vergi Dairesi=Vergi Dairesi"
language_tr = language_tr & "||Vergi Numarası=Vergi Numarası"
language_tr = language_tr & "||Şehir=Şehir"
language_tr = language_tr & "||Cari Türü=Cari Türü"
language_tr = language_tr & "||Telefon=Telefon"
language_tr = language_tr & "||Posta Kodu=Posta Kodu"
language_tr = language_tr & "||Email Adresi=Email Adresi"
language_tr = language_tr & "||Posta Adresi=Posta Adresi"
language_tr = language_tr & "||Şehir Ekle=Şehir Ekle"
language_tr = language_tr & "||Şehir Adını Yazın=Şehir Adını Yazın"
language_tr = language_tr & "||Teklif Ver=Teklif Ver"
language_tr = language_tr & "||Cari Ad veya Kod=Cari Ad veya Kod"
language_tr = language_tr & "||CARİ ARA=CARİ ARA"
language_tr = language_tr & "||Seç=Seç"
language_tr = language_tr & "||Bildirim Yöntemi=Bildirim Yöntemi"
language_tr = language_tr & "||Etiket=Etiket"
language_tr = language_tr & "||Teklif Düzenle=Teklif Düzenle"
language_tr = language_tr & "||PDF=PDF"
language_tr = language_tr & "||Teklifi Düzenle=Teklifi Düzenle"
language_tr = language_tr & "||Önizleme=Önizleme"
language_tr = language_tr & "||PDF Oluştur=PDF Oluştur"
language_tr = language_tr & "||Teklifi Onayla=Teklifi Onayla"
language_tr = language_tr & "||Teklifi Sil=Teklifi Sil"
language_tr = language_tr & "||Email Gönder=Email Gönder"
language_tr = language_tr & "||Mail Gönderimi=Mail Gönderimi"
language_tr = language_tr & "||Mail Gönder=Mail Gönder"
language_tr = language_tr & "||Şablonu Düzenle=Şablonu Düzenle"
language_tr = language_tr & "||Şablonu Sil=Şablonu Sil"
language_tr = language_tr & "||Ek Dosya=Ek Dosya"
language_tr = language_tr & "||Adres Grubunu Düzenle=Adres Grubunu Düzenle"
language_tr = language_tr & "||Adres Grubunu Sil=Adres Grubunu Sil"
language_tr = language_tr & "||Grup içindeki adresleri incele=Grup içindeki adresleri incele"
language_tr = language_tr & "||Koşulu Sil=Koşulu Sil"
language_tr = language_tr & "||Gönder=Gönder"
language_tr = language_tr & "||Onay=Onay"
language_tr = language_tr & "||Teklifler=Teklifler"
language_tr = language_tr & "||Bekliyor=Bekliyor"
language_tr = language_tr & "||Red=Red"
language_tr = language_tr & "||Tümü=Tümü"
language_tr = language_tr & "||TRY=TRY"
language_tr = language_tr & "||EUR=EUR"
language_tr = language_tr & "||USD=USD"
language_tr = language_tr & "||Departman=Departman"
language_tr = language_tr & "||Hava Durumu=Hava Durumu"
language_tr = language_tr & "||Dashboard dizilimini değiştir=Dashboard dizilimini değiştir"
language_tr = language_tr & "||Modulü Sil=Modulü Sil"
language_tr = language_tr & "||Adresi Listeden Kaldır=Adresi Listeden Kaldır"
language_tr = language_tr & "||Teklifi Amir Onaylına Gönder=Teklifi Amir Onaylına Gönder"
language_tr = language_tr & "||Teklif sonucunu seçiniz=Teklif sonucunu seçiniz"
language_tr = language_tr & "||Grup Atamaları=Grup Atamaları"
language_tr = language_tr & "||Grup Adı=Grup Adı"
language_tr = language_tr & "||{%1} için grup abonelikleri={%1} için grup abonelikleri"
language_tr = language_tr & "||Banka Düzenle=Banka Düzenle"
language_tr = language_tr & "||Yeni Mail Şablonu Ekle=Yeni Mail Şablonu Ekle"
language_tr = language_tr & "||Yeni SMS Şablonu Ekle=Yeni SMS Şablonu Ekle"
language_tr = language_tr & "||Başlık=Başlık"
language_tr = language_tr & "||İçerik=İçerik"
language_tr = language_tr & "||Firma Düzenle=Firma Düzenle"
language_tr = language_tr & "||Teklif ayarlarını görmek için yeterli yetkiniz bulunmamaktadır=Teklif ayarlarını görmek için yeterli yetkiniz bulunmamaktadır"
language_tr = language_tr & "||Anlık=Anlık"
language_tr = language_tr & "||Yarın=Yarın"
language_tr = language_tr & "||En Yüksek=En Yüksek"
language_tr = language_tr & "||En Düşük=En Düşük"
language_tr = language_tr & "||Gece=Gece"
language_tr = language_tr & "||Nem=Nem"
language_tr = language_tr & "||Döviz Kurları=Döviz Kurları"
language_tr = language_tr & "||Özel Kur Güncelle=Özel Kur Güncelle"
language_tr = language_tr & "||TCMBden Çek=TCMBden Çek"
language_tr = language_tr & "||Hesapla=Hesapla"
language_tr = language_tr & "||HAYIR=HAYIR"
language_tr = language_tr & "||EVET=EVET"
language_tr = language_tr & "||Hazırlanıyor=Hazırlanıyor"
language_tr = language_tr & "||Amir Onayında=Amir Onayında"
language_tr = language_tr & "||Amir Onaylı=Amir Onaylı"
language_tr = language_tr & "||Amir Red=Amir Red"
language_tr = language_tr & "||Müşteriye Gönderildi=Müşteriye Gönderildi"
language_tr = language_tr & "||Müşteri Red=Müşteri Red"
language_tr = language_tr & "||Satış Gerçekleşti=Satış Gerçekleşti"
language_tr = language_tr & "||Ödeme Bekleniyor=Ödeme Bekleniyor"
language_tr = language_tr & "||Sevkiyatta=Sevkiyatta"
language_tr = language_tr & "||Firma Adı=Firma Adı"
language_tr = language_tr & "||Türkçe=Türkçe"
language_tr = language_tr & "||İngilizce=İngilizce"
language_tr = language_tr & "||Teklif Türü=Teklif Türü"
language_tr = language_tr & "||Kdv Dahil Toplamlı Teklif=Kdv Dahil Toplamlı Teklif"
language_tr = language_tr & "||Kdv Hariç Toplamlı Teklif=Kdv Hariç Toplamlı Teklif"
language_tr = language_tr & "||Genel Teklif=Genel Teklif"
language_tr = language_tr & "||Mail Order=Mail Order"
language_tr = language_tr & "||Taksitli Mail Order=Taksitli Mail Order"
language_tr = language_tr & "||İhracat Teklif=İhracat Teklif"
language_tr = language_tr & "||Proforma Fatura=Proforma Fatura"
language_tr = language_tr & "||Proforma Fatura=Proforma Fatura"
language_tr = language_tr & "||Yazı Yeri=Yazı Yeri"
language_tr = language_tr & "||Neresi=Neresi"
language_tr = language_tr & "||="
language_tr = language_tr & "||Ürün Altı=Ürün Altı"
language_tr = language_tr & "||Teklif Üstü=Teklif Üstü"
language_tr = language_tr & "||Teklif Altı=Teklif Altı"
language_tr = language_tr & "||Detay=Detay"
language_tr = language_tr & "||Adet=Adet"
language_tr = language_tr & "||Birim Fiyatı=Birim Fiyatı"
language_tr = language_tr & "||Toplam=Toplam"
language_tr = language_tr & "||Toplam İskonto=Toplam İskonto"
language_tr = language_tr & "||Genel Toplam=Genel Toplam"
language_tr = language_tr & "||Ara Toplam=Ara Toplam"
language_tr = language_tr & "||Toplam KDV=Toplam KDV"
language_tr = language_tr & "||Banka Adı=Banka Adı"
language_tr = language_tr & "||IBAN=IBAN"
language_tr = language_tr & "||Hesap Döviz Türü=Hesap Döviz Türü"
language_tr = language_tr & "||Yeni Banka Ekle=Yeni Banka Ekle"
language_tr = language_tr & "||Hesap Adı=Hesap Adı"
language_tr = language_tr & "||Şube No=Şube No"
language_tr = language_tr & "||Şube Adı=Şube Adı"
language_tr = language_tr & "||Hesap No=Hesap No"
language_tr = language_tr & "||SWIFT Kodu=SWIFT Kodu"
language_tr = language_tr & "||Kullanım Dışı=Kullanım Dışı"
language_tr = language_tr & "||Mamul=Mamul"
language_tr = language_tr & "||Yarı Mamul=Yarı Mamul"
language_tr = language_tr & "||Bileşen=Bileşen"
language_tr = language_tr & "||Hammadde=Hammadde"
language_tr = language_tr & "||Silindi=Silindi"
language_tr = language_tr & "||Stok Sıfır Olanları Göster=Stok Sıfır Olanları Göster"
language_tr = language_tr & "||Silinmişleri Göster=Silinmişleri Göster"
language_tr = language_tr & "||Toplu Ürün Yükle=Toplu Ürün Yükle"
language_tr = language_tr & "||Muhasebe Yazılımı ile Senkronize Et=Muhasebe Yazılımı ile Senkronize Et"
language_tr = language_tr & "||Yeni Ürün Ekle=Yeni Ürün Ekle"
language_tr = language_tr & "||Ürün Kodu=Ürün Kodu"
language_tr = language_tr & "||Barkod=Barkod"
language_tr = language_tr & "||Stok Miktarı=Stok Miktarı"
language_tr = language_tr & "||Stok Türü=Stok Türü"
language_tr = language_tr & "||Entegrasyon=Entegrasyon"
language_tr = language_tr & "||Ürün Bilgilerini Düzenle=Ürün Bilgilerini Düzenle"
language_tr = language_tr & "||Metre=Metre"
language_tr = language_tr & "||Metrekare=Metrekare"
language_tr = language_tr & "||Santimetre=Santimetre"
language_tr = language_tr & "||Çift=Çift"
language_tr = language_tr & "||Düzine=Düzine"
language_tr = language_tr & "||Rulo=Rulo"
language_tr = language_tr & "||Bidon=Bidon"
language_tr = language_tr & "||Kutu=Kutu"
language_tr = language_tr & "||Koli=Koli"
language_tr = language_tr & "||Paket=Paket"
language_tr = language_tr & "||Ürün Bilgileri=Ürün Bilgileri"
language_tr = language_tr & "||Temel Bilgiler=Temel Bilgiler"
language_tr = language_tr & "||Koli Tanımları=Koli Tanımları"
language_tr = language_tr & "||Stok Temel Bilgileri=Stok Temel Bilgileri"
language_tr = language_tr & "||Katalog Kodu=Katalog Kodu"
language_tr = language_tr & "||Ürünün İngilizce Adı=Ürünün İngilizce Adı"
language_tr = language_tr & "||Fiyat Bilgileri=Fiyat Bilgileri"
language_tr = language_tr & "||Teklif Fiyatı=Teklif Fiyatı"
language_tr = language_tr & "||TL Fiyatı=TL Fiyatı"
language_tr = language_tr & "||KDV Oranı=KDV Oranı"
language_tr = language_tr & "||KDV=KDV"
language_tr = language_tr & "||Depolama Bilgileri=Depolama Bilgileri"
language_tr = language_tr & "||Minumum Stok Miktarı=Minumum Stok Miktarı"
language_tr = language_tr & "||Raf Ömrü (Ay)=Raf Ömrü (Ay)"
language_tr = language_tr & "||Ay=Ay"
language_tr = language_tr & "||Ürün Ana Birimi=Ürün Ana Birimi"
language_tr = language_tr & "||LOT Takibi Yapılsın=LOT Takibi Yapılsın"
language_tr = language_tr & "||Koli, koli bandı gibi sarf malzemelerde LOT takibi yapılmayacağı için bu tip ürünlerde HAYIR seçilir.=Koli, koli bandı gibi sarf malzemelerde LOT takibi yapılmayacağı için bu tip ürünlerde HAYIR seçilir."
language_tr = language_tr & "||Mal Kabul Kalite Kontrol Deposundan Mı Yapılsın?=Mal Kabul Kalite Kontrol Deposundan Mı Yapılsın?"
language_tr = language_tr & "||Seçilen Koli=Seçilen Koli"
language_tr = language_tr & "||Kullanılacak ham koli seçimi=Kullanılacak ham koli seçimi"
language_tr = language_tr & "||Koli İçi Ürün Miktarı=Koli İçi Ürün Miktarı"
language_tr = language_tr & "||Ekle=Ekle"
language_tr = language_tr & "||Koli Adı=Koli Adı"
language_tr = language_tr & "||Kullanılan Koli Adı=Kullanılan Koli Adı"
language_tr = language_tr & "||Lütfen ürün için bir stok kodu yazın.=Lütfen ürün için bir stok kodu yazın."
language_tr = language_tr & "||Seçtiğiniz kriterlerde kayıt bulunamadı=Seçtiğiniz kriterlerde kayıt bulunamadı"
language_tr = language_tr & "||Hata Oluştu=Hata Oluştu"
language_tr = language_tr & "||Bu alana girmek için yetkiniz yeterli değil.=Bu alana girmek için yetkiniz yeterli değil."
language_tr = language_tr & "||Cari Adı, Cari Kodu=Cari Adı, Cari Kodu"
language_tr = language_tr & "||Sayı=Sayı"
language_tr = language_tr & "||Sonuç=Sonuç"
language_tr = language_tr & "||Teklifi Amir Onayına Gönder?=Teklifi Amir Onayına Gönder?"
language_tr = language_tr & "||Amir Onayına Gönder=Amir Onayına Gönder"
language_tr = language_tr & "||Gönderme=Gönderme"
language_tr = language_tr & "||Cari Seçimi=Cari Seçimi"
language_tr = language_tr & "||Müşteri Bilgileri=Müşteri Bilgileri"
language_tr = language_tr & "||Sayın=Sayın"
language_tr = language_tr & "||Sayı : (Boş bırakırsanız otomatik oluşur)=Sayı : (Boş bırakırsanız otomatik oluşur)"
language_tr = language_tr & "||Teklif Tarihi=Teklif Tarihi"
language_tr = language_tr & "||Teklif Ayarları=Teklif Ayarları"
language_tr = language_tr & "||Teklif Veren Firma=Teklif Veren Firma"
language_tr = language_tr & "||Teklif Dili=Teklif Dili"
language_tr = language_tr & "||Teklif Para Birimi=Teklif Para Birimi"
language_tr = language_tr & "||Teklif Tasarımı=Teklif Tasarımı"
language_tr = language_tr & "||Teklif Ön Yazısı=Teklif Ön Yazısı"
language_tr = language_tr & "||Hazır Yazı=Hazır Yazı"
language_tr = language_tr & "||Üst Yazı=Üst Yazı"
language_tr = language_tr & "||Ürünler=Ürünler"
language_tr = language_tr & "||Teklif Verilecek Ürün=Teklif Verilecek Ürün"
language_tr = language_tr & "||Ürün adı, stok kodu, barkod=Ürün adı, stok kodu, barkod"
language_tr = language_tr & "||Teklife Özel Not=Teklife Özel Not"
language_tr = language_tr & "||Ticari Koşullar=Ticari Koşullar"
language_tr = language_tr & "||Koşul Seçin=Koşul Seçin"
language_tr = language_tr & "||Teklif Alt Yazısı=Teklif Alt Yazısı"
language_tr = language_tr & "||Alt Yazı=Alt Yazı"
language_tr = language_tr & "||Ürün eklemeden önce teklif verilecek olan firmaya ait cari bilgilerini girmelisiniz.=Ürün eklemeden önce teklif verilecek olan firmaya ait cari bilgilerini girmelisiniz."
language_tr = language_tr & "||Lütfen bir ürün seçin.=Lütfen bir ürün seçin."
language_tr = language_tr & "||Birim Fiyat=Birim Fiyat"
language_tr = language_tr & "||Satır Toplamı=Satır Toplamı"
language_tr = language_tr & "||Teklife ürün ekleniyor=Teklife ürün ekleniyor"
language_tr = language_tr & "||Teklif para birimi {%1} ile stok para birimi {%2} farklılar=Teklif para birimi {%1} ile stok para birimi {%2} farklılar"
language_tr = language_tr & "||Ürün Notu=Ürün Notu"
language_tr = language_tr & "||Birim=Birim"
language_tr = language_tr & "||Perakende Satış Fiyatı=Perakende Satış Fiyatı"
language_tr = language_tr & "||Toptan Satış Fiyatı=Toptan Satış Fiyatı"
language_tr = language_tr & "||USD Fiyatı=USD Fiyatı"
language_tr = language_tr & "||İskonto=İskonto"
language_tr = language_tr & "||Toplam Fiyat=Toplam Fiyat"
language_tr = language_tr & "||Teklif Kaydedildi=Teklif Kaydedildi"
language_tr = language_tr & "||Koşullar=Koşullar"
language_tr = language_tr & "||Koşul=Koşul"
language_tr = language_tr & "||Koşulu silmek mi istiyorsunuz?=Koşulu silmek mi istiyorsunuz?"
language_tr = language_tr & "||Silme=Silme"
language_tr = language_tr & "||Üst Yazılar=Üst Yazılar"
language_tr = language_tr & "||Teklifi Onaylıyor Musunuz?=Teklifi Onaylıyor Musunuz?"
language_tr = language_tr & "||Teklifi Reddet=Teklifi Reddet"
language_tr = language_tr & "||Döviz kurları yazdığınız şekilde güncellendi=Döviz kurları yazdığınız şekilde güncellendi"
language_tr = language_tr & "||Tamam=Tamam"
language_tr = language_tr & "||Yeni döviz kurları:=Yeni döviz kurları:"
language_tr = language_tr & "||Döviz kurları merkez bankasından çekildi ve güncellendi=Döviz kurları merkez bankasından çekildi ve güncellendi"
language_tr = language_tr & "||Silinmişleri Gizle=Silinmişleri Gizle"
language_tr = language_tr & "||Stok Sıfır Olanları Gizle=Stok Sıfır Olanları Gizle"
language_tr = language_tr & "||Yok=Yok"
language_tr = language_tr & "||Ek Bilgiler=Ek Bilgiler"
language_tr = language_tr & "||Lütfen ürüne ait ana birimi seçin=Lütfen ürüne ait ana birimi seçin"
language_tr = language_tr & "||Ürüne ait KDV ORANI bilgisini seçiniz=Ürüne ait KDV ORANI bilgisini seçiniz"
language_tr = language_tr & "||Ürüne ait fiyat bilgisini yazınız=Ürüne ait fiyat bilgisini yazınız"
language_tr = language_tr & "||Ürüne ait para birimi bilgisini seçiniz=Ürüne ait para birimi bilgisini seçiniz"
language_tr = language_tr & "||Yeni ürün eklendi=Yeni ürün eklendi"
language_tr = language_tr & "||Veri Aktarımı=Veri Aktarımı"
language_tr = language_tr & "||Verileri İçeri Al=Verileri İçeri Al"
language_tr = language_tr & "||Verileri Dışarı Aktar=Verileri Dışarı Aktar"
language_tr = language_tr & "||Ürün hareket görmüş, Ana birim değiştirilemez.=Ürün hareket görmüş, Ana birim değiştirilemez."
language_tr = language_tr & "||Senkronize Muhasebe Yazılımına Kaydet=Senkronize Muhasebe Yazılımına Kaydet"
language_tr = language_tr & "||Ürün ID=Ürün ID"
language_tr = language_tr & "||Fiyat=Fiyat"
language_tr = language_tr & "||Döviz kurlarını güncelleme yetkiniz bulunmamaktadır=Döviz kurlarını güncelleme yetkiniz bulunmamaktadır"
language_tr = language_tr & "||Ürünün Barkodu=Ürünün Barkodu"
language_tr = language_tr & "||İşlem yaptığınız ürün bilgileri muhasebe yazılımınız ile entegre şekilde ayarlanmış. Güncellemeleri muhasebe yazılımınız üzerinden yapmalısınız.=İşlem yaptığınız ürün bilgileri muhasebe yazılımınız ile entegre şekilde ayarlanmış. Güncellemeleri muhasebe yazılımınız üzerinden yapmalısınız."
language_tr = language_tr & "||Cari Listesi Ekranı=Cari Listesi Ekranı"
language_tr = language_tr & "||Müşteri Adı=Müşteri Adı"
language_tr = language_tr & "||Yeni Cari Ekle=Yeni Cari Ekle"
language_tr = language_tr & "||Tanımlanmamış=Tanımlanmamış"
language_tr = language_tr & "||Ürün bilgileri güncellendi=Ürün bilgileri güncellendi"
language_tr = language_tr & "||Cari Bilgilerini Düzenle=Cari Bilgilerini Düzenle"
language_tr = language_tr & "||Telefonu=Telefonu"
language_tr = language_tr & "||Email=Email"
language_tr = language_tr & "||Firma Türü=Firma Türü"
language_tr = language_tr & "||Cari Ayrıntıları EkranıMALATYA 7. ANA JET ÜSSÜ=Cari Ayrıntıları EkranıMALATYA 7. ANA JET ÜSSÜ"
language_tr = language_tr & "||Cari Ayrıntıları Ekranı=Cari Ayrıntıları Ekranı"
language_tr = language_tr & "||Cari GüncellemeMALATYA 7. ANA JET ÜSSÜ=Cari GüncellemeMALATYA 7. ANA JET ÜSSÜ"
language_tr = language_tr & "||Lütfen cari adını yazın=Lütfen cari adını yazın"
language_tr = language_tr & "||Kayıt Güncellendi=Kayıt Güncellendi"
language_tr = language_tr & "||Cari Eklemeqq=Cari Eklemeqq"
language_tr = language_tr & "||Kayıt Yapıldı=Kayıt Yapıldı"
language_tr = language_tr & "||Cari Ayrıntıları Ekranıqq=Cari Ayrıntıları Ekranıqq"
language_tr = language_tr & "||Cari Güncellemeqq=Cari Güncellemeqq"
language_tr = language_tr & "||Cari Eklemer=Cari Eklemer"
language_tr = language_tr & "||Son Kullanıcı=Son Kullanıcı"
language_tr = language_tr & "||Bayi=Bayi"
language_tr = language_tr & "||Tedarikçi=Tedarikçi"
language_tr = language_tr & "||İl=İl"
language_tr = language_tr & "||Vergi No=Vergi No"
language_tr = language_tr & "||Teklifdeki ürün güncelleniyor=Teklifdeki ürün güncelleniyor"
language_tr = language_tr & "||Kritik Hata Oluştu. Teklif PDF için uygun rapor formatı bulunamadı=Kritik Hata Oluştu. Teklif PDF için uygun rapor formatı bulunamadı"
language_tr = language_tr & "||Teklif raporu formatı bulunamadı=Teklif raporu formatı bulunamadı"
language_tr = language_tr & "||Müşteri Kodu=Müşteri Kodu"
language_tr = language_tr & "||KDV Hariç=KDV Hariç"
language_tr = language_tr & "||Ön izleme için lütfen bir şablon seçin=Ön izleme için lütfen bir şablon seçin"
language_tr = language_tr & "||Arşiv=Arşiv"
language_tr = language_tr & "||Şablonu Çoğalt=Şablonu Çoğalt"
if klang = "" then
klang = "tr"
end if
if klang = "en" then
hedefSozluk = language_en
else
hedefSozluk = language_tr
end if
languageSozluk = Split(hedefSozluk,"||")
%>